### ISSUE TITLE
Support stop_on_invalid_record option

### ISSUE THREAD

**Issue by muga** [civitaspo/embulk-filter-expand_json#14]
I noticed that all processing (Embulk itself) fails if one record cannot be expanded by this plugin.
https://github.com/civitaspo/embulk-filter-expand_json/blob/master/src/main/java/org/embulk/filter/expand_json/FilteredPageOutput.java#L205-L217

I want to add `stop_on_invalid_record` option in this plugin like CsvParserPlugin. If this option enabled, all processing will stop when it found invalid record. If disabled, the invalid record only will be skipped. It's better that this option's default value is false like CsvParserPlugin, I think. But the behavior of the current plugin is true. 
https://github.com/embulk/embulk/blob/master/embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java#L96

How do you think about it?

**Comment by civitaspo** [comment]
> I want to add `stop_on_invalid_record` option in this plugin like CsvParserPlugin.

Good idea! But, I want to consider the option is the best way to avoid invalid records.
For example, BigQuery has `max_bad_records` option. This option can make us know as Exception that
number of records of more than imagination are treated as invalid.
In my case, `stop_on_invalid_record` option is enough because we do not allow storing invalid records continuously.
In your case, which option is the best?

**Comment by muga** [comment]
Thank you for comments. Just in case, What I want is to skip invalid records that the plugin recognized.

To do that, `stop_on_invalid_record` option is better for current Embulk architecture. In the current Embulk architecture, parser and filter plugins don't have the way for counting up the # of records that they processed instead of input and output plugins. Since the filter plugin's tasks can know the # of records that they processed, we might be able to take the idea `max_bad_records_per_task`. But I don't know that it's good or not (personally it doesn't make sense so much). Therefore, CsvParserPlugin took `stop_on_invalid_record` option.

How about `skip_on_invalid_record` option? :-)

FYI: as another idea, Embulk should have metrics in the future. But it's not short-term.
https://github.com/embulk/embulk/issues/199

**Comment by muga** [comment]
> How about `skip_on_invalid_record` option? :-)

`skip_on_invalid_record` option is almost same as `stop_on_invalid_record`. Not best but `stop_on_invalid_record` is better.

**Comment by civitaspo** [comment]
Thanx for the comment.

> In the current Embulk architecture, ......

ok, I understand. So, `stop_on_invalid_record` looks better for me, too.

> FYI: as another idea, Embulk should have metrics in the future. But it's not short-term.
> embulk/embulk#199

I'm looking forward to this!

**Comment by muga** [comment]
Thank you for considering about it. I implemented it on https://github.com/civitaspo/embulk-filter-expand_json/pull/15. Can you review it? If it's ok, please merge and release new version.

**Comment by muga** [comment]
closed
