### ISSUE TITLE
Feature request: allow user to specify added column name

### ISSUE THREAD

**Issue by bcipolli** [civitaspo/embulk-filter-expand_json#25]
Currently, it looks like the column name of the added column is computed from the JSONPath used to find the value for the row.

I would like to control the names of my added columns. It would be great (and seemingly not hard) to add an `alias` property to `expanded_columns` values, that overrides the default column name computation.

**Comment by civitaspo** [comment]
@bcipolli thanks for the feature request. But I think this plugin should focus on `expand_json`. That `alias` function is implemented by [`embulk-filter-rename` plugin](http://www.embulk.org/docs/built-in.html#rename-filter-plugin). How do you use this plugin? Do you have any opinion that `embulk-filter-expand_json` should have the `alias` function?

**Comment by bcipolli** [comment]
Ah, I see. Sure, if I can combine with another plugin, that's fine for me! Thank you!

**Comment by civitaspo** [comment]
Good. If you have anything else contact me.
