### ISSUE TITLE
Adding support for type conversion from floating point numbers to integers

### ISSUE THREAD

**Issue by frsyuki** [civitaspo/embulk-filter-expand_json#32]
JSON doesn't distinguish integers from floating point numbers. Both of them are number.
There is a confusion around type conversion due to this issue as we got a report at https://github.com/embulk/embulk/issues/775.

For this characteristic of JSON, I think it is reasonable idea to add an automatic conversion from floating point numbers to `long` type in expand_json filter plugin. Even if the source number contains some fraction numbers, rounding it to long is acceptable.

**Comment by frsyuki** [comment]
Here is an example configuration to reproduce the issue: https://github.com/hiroyuki-sato/embulk-support/tree/master/test_json_double

This example patch fixes the issue: https://t.co/8eTUVwGtGv

**Comment by civitaspo** [comment]
Thank a lot. I fix this by your patch.

ref. (In Japanese) https://twitter.com/smdmts/status/905655973418754051
